# Generated by Django 4.2 on 2025-04-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roxsy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('PULSERA', 'PULSERA'), ('COLLAR', 'COLLAR'), ('ARETE', 'ARETE')], max_length=10, null=True),
        ),
    ]
